version: '3.7'

services:
  etsis: 
    #image: edutrac-sis 
    image: 192.87.106.18:56001/edutrac:0.1
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: '1.0'
          memory: 256M
      restart_policy:
        condition: any
    secrets:
      - edutrac_db_root_password
      - edutrac_db_dba_password
    environment:
      DB_HOST: ${STACK_SERVICE}_db
      DB_USER: 'dba'
      DB_NAME: 'sis'
      DB_PASS_FILE: /run/secrets/edutrac_db_dba_password
      DB_PORT: 3306
    networks:
      - $STACK_NETWORK
    ports:
      - $STACK_PORT:80
    volumes:
      #- /var/docker/image-edutrac-sis/public_html/:/var/www/html/
      - /mnt/nfs/nfsdlo/$STACK_NETWORK/$STACK_SERVICE/$STACK_VERSION/html:/var/www/html/
      - /mnt/nfs/nfsdlo/$STACK_NETWORK/$STACK_SERVICE/$STACK_VERSION/conf:/var/www/conf/
      - /mnt/nfs/nfsdlo/$STACK_NETWORK/$STACK_SERVICE/$STACK_VERSION/tmp/startup.sh:/startup.sh

  db:
    #image: mysql:5.7 
    image: 192.87.106.18:56001/mysql:0.1
    secrets:
      - edutrac_db_root_password
      - edutrac_db_dba_password
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: '1.0'
          memory: 512M
      restart_policy:
        condition: any
        delay: 60s
      placement:
        constraints: [node.role == manager]
    environment:
      MYSQL_USER: dba
      MYSQL_DATABASE: sis 
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/edutrac_db_root_password
      MYSQL_PASSWORD_FILE: /run/secrets/edutrac_db_dba_password
    networks:
      - $STACK_NETWORK
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      #- .data/mysql:/var/lib/mysql
      - /mnt/nfs/nfsdlo/$STACK_NETWORK/$STACK_SERVICE/$STACK_VERSION/data/mysql:/var/lib/mysql

    configs:
      - source: my_cnf
        target: /etc/mysql/conf.d/my.cnf

secrets:
  edutrac_db_root_password:
    external: true
  edutrac_db_dba_password:
    external: true

configs:
  my_cnf:
    external: true

networks:
  dev-net:
    external: true
  test-net:
    external: true
  exp-net:
    external: true
